language: cpp
os: windows
env:
  - MSBUILD="/c/Program Files (x86)/Microsoft Visual Studio/2017/BuildTools/MSBuild/15.0/Bin/MSBuild.exe"
jobs:
  include:
    - stage: Compile
      script: $MSBUILD -t:Clean -t:Build
    - stage: Test
      script: ./test.sh
